### ISSUE TITLE
Paid for Shopgoodwill sniper but 

### ISSUE THREAD

**Issue by art2gecko** [Auction-Sniping/Auction-Sniper#8]
Installed the Shopgoodwill Sniper

Paid for the software and now when I enter Auction ID on the bottom and enter maximum bid it doesnt add it.

It also doesn't add sniper on the auction listing detail page where it says "Place My Bid" and below it Snipe My Bid

Not sure if I installed it incorrectly.

**Comment by Auction-Sniping** [comment]
Hi art2gecko,

Thank you for your order! Ok, have you installed it from the Windows Store app or directly from SGWSniper.com? FYI, the version on the Windows Store is available here:

https://apps.microsoft.com/detail/auction-sniper/9NLHNKNJM66J?hl=en-us&gl=US

Or you can install it directly from SGWSniper.com

Simply download the zip file, extract it's contents, and then double click the installer file in there and it will do the rest automatically for you and Ince the installation is successful you will find the shortcut on your desktop.

So regarding the installation, that is how you can install the app, there are 2 different ways as mentioned above you can pick your favorite way, the Windows store method is alot faster because it's only one click and the other method is 4 clicks... I personally recommend installing the Windows store version as it's only 70MB and the other one is 500MB because they are packaged different, but here is a video on how to install the other version in case you want to watch how to do it on YouTube:

https://www.youtube.com/watch?v=Bee4D1jd3E4

Now regarding activation, it sounds like your firewall may have blocked the activation, so please try exiting the app and restarting your computer, then once your computer reboots, disable your Windows firewall temporarily for the activation process, then once you are done activating the software you can enable your windows firewall again, now since you already paid, I have included a coupon code below that will skip the payment again so that you can try to activate the software again:

Coupon Code: MYEEOVSY

Please let us know if you need further assistance!

We appreciate your business and support,
Customer Service

**Comment by art2gecko** [comment]
I added a bunch of snipes and got an error message

The request is blocked on the shopgoodwill sign in.

**Comment by Auction-Sniping** [comment]
Hi art2gecko,

Sometimes their website goes up and down, please exit the app and if you have Google Chrome web browser install please open it and completely clear your cache, and then also delete the following folder off your computer:

C:\Users\<YOUR WINDOWS USERNAME>\AppData\Roaming\ShopGoodwill Sniper

and/or:

C:\Users\<YOUR WINDOWS USERNAME>\AppData\Roaming\Auction Sniper

Replace YOUR WINDOWS USERNAME in the path above with your Windows username. Then restart the app.

Please let us know if the problem still persists and we may need to do a screen sharing and help you!

Sincerely,
Technical Support

**Comment by art2gecko** [comment]
Ok I will try that.

Finally, do the snipes save? How do I reload them after exiting the app?

**Comment by Auction-Sniping** [comment]
Yes, the snipes save and reload after restarting the app but since you deleted the folder above they will be deleted also, so you may need to reenter them but it sounds like they have blocked your login account, so please create a new account with them on the shopgoodwill website and also you may need a new coupon code so please let me know if it asks you for payment, but definitely create a completely new shopgoodwill account and be sure to completely clear your cache before doing so their system doesn't relate your old account to your new account, it sounds like they have blocked your actual login account, not your IP address.

**Comment by art2gecko** [comment]
Hi, I managed to get it working for a day or two.

I download the app from Microsoft Store and used it a few times.

I am trying to add snipes today and there is nothing being added to the
queue.

**Comment by Auction-Sniping** [comment]
Hi art2gecko,

Please try installing the version from SGWSniper.com because it is the most recent!

Thank you,
Technical Support

**Comment by art2gecko** [comment]
So I did what you recommended. It loaded one SNIPE and the second snipe is
asking for a payment.

**Comment by Auction-Sniping** [comment]
Please use the following coupon code when it asks for payment, but before you do that please exit the app and disable your windows firewall first, and then go thru the activation process:

JLEXDVXM

After the activation is complete, you may need to exit the app and open it again and then you should be all set after that!

**Comment by art2gecko** [comment]
I tried what you recommended.

I really want to use this software honestly. I paid 250 for a license and
another 100 for another desktop.

Can we schedule a time for you to teamviewer this problem?

**Comment by art2gecko** [comment]
I reinstalled it.

Followed your instructions and activated it.

Still wont add the snipes.

**Comment by Auction-Sniping** [comment]
I think I know what it might be, let me make some modifications to the software and I will post a new version, it might be your cache is corrupted... I will get back to you in a few days...

Thank you for your patience! 
Technical Support

**Comment by Auction-Sniping** [comment]
Hi art2gecko,

I just wanted to let you know that we just posted an update, please download the new version from SGWSniper.com and just install over your old version and then try adding some snipes again so we can see if that solved the problem? If the problem still persists, can you please take a video screen record of the problem occurring and send it to me either via YouTube or email to help@snipeable.com?

Thank you!
Technical Support

**Comment by art2gecko** [comment]
Oh great. Now its not. Let me try this.

**Comment by art2gecko** [comment]
The archive is either in unknown format or damaged. That is the error when
unzipping the new download from your website

**Comment by Auction-Sniping** [comment]
Yes, you're right our download server was down please try again now.
